apiVersion: v1
kind: Namespace
metadata:
  name: finance-website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 3000
          env:
            - name: CAR_VERSION
              value: "{{ .Values.imageTag }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort
