apiVersion: v1
kind: Namespace
metadata:
  name: finance-website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-website-broken
  namespace: finance-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-website-broken
  template:
    metadata:
      labels:
        app: car-website-broken
    spec:
      containers:
        - name: car-website-broken
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 3000
          env:
            - name: CAR_VERSION
              value: "{{ .Values.imageTag }}"
---
apiVersion: v1
kind: Service
metadata:
  name: car-website-broken
  namespace: finance-website
spec:
  selector:
    app: car-website-broken
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31108
  type: NodePort
